### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Aex12** [Ivshti/addon-helloworld#1]
I am researching on how to make my own addon to add content to strem.io and I found this repository.
I can run it on node without error, and include it on strem.io
It shows under addons tab and I activate it. But when I search for Fight Club and I click on View film button the magnet that this addons attach doesnt display.

Sorry for my bad english

**Comment by Ivshti** [comment]
does a tab appear in Discover?
do the other movies this add-on provides work?

**Comment by Aex12** [comment]
Yes, tab appear in discover, but it show different movies than hardcoded on this addon. I tested with all the films on dataset arrays and no one is showing up. I am going to attach some photos:
http://imgur.com/a/GL4m9

**Comment by Ivshti** [comment]
What do you mean "showing up". where do you expect them to show up? You have to click on the tab of the add-on, there the movies of the add-on should appear

Once you click on the movie itself and then play, a stream should appear from this add-on.

That's the expected behaviour.

**Comment by Aex12** [comment]
As you can see on photos that I attached it is not working at expected. I want to make an addon to retrieve torrents files and stream them from mejor torrent.com but I cant find any documentation of addon system, and the sample plugin is not working properly so I cannot do anything

**Comment by Ivshti** [comment]
The docs are here: https://github.com/Stremio/stremio-addons

Now I see what you mean by "not working as expected". I only saw the first image before, sorry.

Can you show me exactly how you're activating it in stremio?

**Comment by Aex12** [comment]
I am using this to install sample addon:
```
git clone https://github.com/Ivshti/addon-helloworld.git
cd addon-helloworld
npm install
nodejs idex
```

And this is what I am using to run stremio with sample-addon:
`./Stremio.sh launch  --service=http://localhost:7000`

**Comment by Ivshti** [comment]
can you try something a bit different at the end:
./Stremio.sh launch --service=http://localhost:7000/stremioget/stremio/v1

**Comment by Aex12** [comment]
Seems like it is working properly launching with this command.

Thanks!

**Comment by Ivshti** [comment]
my guess would be incompatibility between stremio-addons versions, one of them requiring a suffix, the other - not

could be something else related to the suffix "/stremioget/stremio/v1"

**Comment by Aex12** [comment]
It is because of the suffix "/stremioget/stremio/v1" because if I rerun stremio without it same thing happens

**Comment by Ivshti** [comment]
if it works with it, but not without it, then yes - that's the reason

**Comment by Aex12** [comment]
Thank you for your support! 

Tomorrow I will start writing my addon. Is there any way to add content that it isn't on imdb?

I want to retrieve torrents from mejortorrent.com (A spanish "database" of torrents). Titles are in spanish so I can't find them on imdb.

**Comment by Ivshti** [comment]
Yes, you can define your own ``id`` property for the particular site the add-on is for
E.g. ``{ id: "mejor:some-movies" }``
Read the "meta" documentation in detail
