### ISSUE TITLE
Stream from .torrent file

### ISSUE THREAD

**Issue by Aex12** [Ivshti/addon-helloworld#2]
It is possible to stream from a .torrent file and not from a magnet? If yes, how can I do it?

I tried returning this: 
`[{ url: "http://www.mejortorrent.com/uploads/torrents/peliculas/Synchronicity_HDRip.torrent", availability: 2 }]`

But when I try to stream it, it never starts.

**Comment by Ivshti** [comment]
You really only need the infoHash and potentially "sources"

It's all documented here: https://github.com/Ivshti/stremio-addons/blob/master/docs/api/stream/stream.response.md

You can also see it in https://github.com/Stremio/stremio-vodo

**Comment by Ivshti** [comment]
If you only get .torrent files from the API, you can download them and parse them with feross's parse-torrent and return infoHash/sources as you can see in stremio-vodo
